<?php

$namesJson=array(
	'SON' => 'Sonora',
	'VER' => 'Veracruz',
	'CHP' => 'Chiapas',
	'OAX' => 'Oaxaca',
	'GRO' => 'Guerrero',
	'TAB' => 'Tabasco',
	'MIC' => 'Michoacán',
	'PUE' => 'Puebla',
	'MOR' => 'Morelos',
	'MEX' => 'México',
	'COL' => 'Colima',
	'CAM' => 'Campeche',
	'JAL' => 'Jalisco',
	'DIF' => 'Distrito Federal',
	'TLA' => 'Tlaxcala',
	'HID' => 'Hidalgo',
	'GUA' => 'Guanajuato',
	'QUE' => 'Querétaro',
	'YUC' => 'Yucatán',
	'ZAC' => 'Zacatecas',
	'SLP' => 'San Luis Potosí',
	'AGU' => 'Aguascalientes',
	'ROO' => 'Quintana Roo',
	'NAY' => 'Nayarit',
	'DUR' => 'Durango',
	'NLE' => 'Nuevo León',
	'COA' => 'Coahuila',
	'SIN' => 'Sinaloa',
	'CHH' => 'Chihuahua',
	'BCS' => 'Baja California Sur',
	'BCN' => 'Baja California',
	'TAM' => 'Tamaulipas'
);
